name: CI/CD for Django Backend

on:
  push:
    branches:
      - rony
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest  # Include your testing framework

    - name: Run tests
      run: |
        python manage.py test

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t readingcorner .

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: readingcornerregistry.azurecr.io
        username: ${{ readingcornerregistry }}
        password: ${{ secrets.HBvZH3bUoKumJ5u3g5L3NS35dWWDnu3AQUy5Mze1O7+ACRDsnURV }}

    - name: Push Docker image
      run: docker push readingcornerregistry.azurecr.io/readingcorner:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az webapp config container set \
          --name readingcorner1 \
          --resource-group ReadingCorner \
          --docker-custom-image-name readingcorner.azurecr.io/readingcorner:latest
