# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - readingcorner1

on:
  push:
    branches:
      - rony
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://readingcornerregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_abce95ef166145719a617ba41a76d6d9 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_44935ebafc7c4bd5a7e53e31974d0816 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: readingcornerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abce95ef166145719a617ba41a76d6d9 }}/readingcorner:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'readingcorner1'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_aec4dd002815441c881740f9d09d2948 }}
            images: 'readingcornerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abce95ef166145719a617ba41a76d6d9 }}/readingcorner:${{ github.sha }}'