services:
  web:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dbAdmin
      POSTGRES_PASSWORD: Reading.Corner
      POSTGRES_DB: ReadingCorner
    ports:
      - "5432:5432"
